ROOT_DIR=../
SCRIPT_PATH="${ROOT_DIR}"/src
DATA_PATH="${ROOT_DIR}"/data
O_FACE="${ROOT_DIR}"/OpenFace/build/bin/FeatureExtraction
CNN_DETECTOR_PATH="${ROOT_DIR}"/mtcnn
export PYTHONPATH=$PYTHONPATH:${CNN_DETECTOR_PATH}
